// this loads env vars
// require('dotenv').config(); 

const AUTH_URL_PATH = "/auth";
const BOARDS_URL_PATH = "/boards";
const LISTS_URL_PATH = "/lists";
const CARDS_URL_PATH = "/cards";
const USERS_URL_PATH = "/users";

const ACCESS_TOKEN_SECRET = require("crypto").randomBytes(64).toString("hex");
const BOARDS_COLLECTION_NAME = "boards";
const USERS_COLLECTION_NAME = "users";
const LISTS_COLLECTION_NAME = "lists";
const CARDS_COLLECTION_NAME = "cards";
const CHECKLISTS_COLLECTION_NAME = "checklists";
const CHECKLISTS_ITEMS_COLLECTION_NAME = "checklistitems";

const API_PORT = process.env.RESTAPI_PORT;

const MONGO_HOST = process.env.MONGO_HOST;
const MONGO_PORT = process.env.MONGO_PORT;
const MONGO_CONNECTION_OPTIONS = process.env.MONGO_CONNECTION_OPTIONS ?
 `?${process.env.MONGO_CONNECTION_OPTIONS}` :
 ``;
const DB_NAME = process.env.MONGO_DATABASE;
const MONGO_USER = process.env.MONGO_USER;
const MONGO_PASSWORD = process.env.MONGO_PASSWORD;
let MONGO_CONNECTION_STRING = null;
if (MONGO_USER && MONGO_PASSWORD) {
  MONGO_CONNECTION_STRING = `mongodb+srv://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_HOST}/${DB_NAME}${MONGO_CONNECTION_OPTIONS}`;
} else {
  MONGO_CONNECTION_STRING = `mongodb://${MONGO_HOST}:${MONGO_PORT}${MONGO_CONNECTION_OPTIONS}`;
}

console.log ("MONGO_CONNECTION_STRING-", MONGO_CONNECTION_STRING);

module.exports = {
  AUTH_URL_PATH,
  BOARDS_URL_PATH,
  LISTS_URL_PATH,
  CARDS_URL_PATH,
  USERS_URL_PATH,
  ACCESS_TOKEN_SECRET,
  DB_NAME,
  BOARDS_COLLECTION_NAME,
  USERS_COLLECTION_NAME,
  LISTS_COLLECTION_NAME,
  CARDS_COLLECTION_NAME,
  CHECKLISTS_COLLECTION_NAME,
  CHECKLISTS_ITEMS_COLLECTION_NAME,
  API_PORT,
  MONGO_CONNECTION_STRING,
};
